# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c7fa953b4193ea3bb79a9d6ec948a8eeac238cfd166c52807d9efb7c3b276bdaa41c9000a22f14126ea7aae2075f44d8803f5dfb524a09d098065cbb35c8846

test:
  secret_key_base: 77fcb09a7bca62ce93e72156bd87391f5560ee6cec5fae42cbfeea8ee67f00b0d87b9c4f7eb230d2ccacf4a4469ae8c1a2960dd2e1815dda5b9164412807ee6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
